INITIAL_TEMPERATURE = 15
MAX_TEMPERATURE = 100
TEMPERATURE_PRECISION = 2  # digits after floating point
POWER = 10000  # 2200
VOLUME = 1.7
SENSOR_TIMEDELTA = 1  # seconds
STATE_CTX_RECEIVER = None
CHANGED_STATE_CTX_RECEIVER = None
